//console.dir(document);
//console.log(document.domain);
//console.log(document.URL);
//console.log(document.title);
//document.title = 123;
//console.log(document.doctype);
//console.log(document.head);
//console.log(document.body);
//console.log(document.getElementById('header-title'));
var headerTtile = document.getElementById('header-title');
console.log(headerTtile);
headerTtile.textContent = 'Hi everyone.';
